import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoMigration1779626606414 implements MigrationInterface {
    name = 'AutoMigration1779626606414'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE SCHEMA IF NOT EXISTS "payments"`);
        await queryRunner.query(`CREATE TABLE "mercantil_clients" ("id" uuid NOT NULL, "shopcartId" character varying(100) NOT NULL, "clientId" character varying(100), "firstName" character varying(255) NOT NULL, "lastName" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "dniType" character varying(20) NOT NULL, "dniNumber" character varying(50) NOT NULL, "dniVenNationality" character varying(10), "birthDate" character varying(20) NOT NULL, "genderId" character varying(10) NOT NULL, "countryOfBirthId" character varying(50), "civilStateId" character varying(50), "phoneCountryId" character varying(20), "phoneAreaCode" character varying(10), "phoneNumber" character varying(20), "addressCountryId" character varying(50), "addressAdministrativeAreaId" character varying(50), "addressSubadministrativeAreaId" character varying(50), "addressLocalityId" character varying(50), "addressZoneId" character varying(50), "addressPostalCode" character varying(20), "addressLine" character varying(255), "rawData" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_afb021afc958448787da5a7e977" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_85ec7fc5de58d0cf8043e5adfd" ON "mercantil_clients"  ("shopcartId") `);
        await queryRunner.query(`CREATE TABLE "mercantil_payment_quotes" ("id" uuid NOT NULL, "shopcartId" character varying(100) NOT NULL, "policyId" character varying(100) NOT NULL, "policyNumber" character varying(100), "quote" character varying(100) NOT NULL, "agreement" integer, "receipt" integer, "receiptStatus" character varying(50), "quoteStatus" character varying(50), "isNextDuePayment" boolean NOT NULL DEFAULT false, "isPaid" boolean NOT NULL DEFAULT false, "amount" numeric(15,2), "expirationDate" character varying(50), "rawData" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_99fe06014fcd5d2aaa5d97e2cd1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_15fab6ed169599f440d983adca" ON "mercantil_payment_quotes"  ("shopcartId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a07a882a57a7a3dd9572689580" ON "mercantil_payment_quotes"  ("policyId") `);
        await queryRunner.query(`CREATE TABLE "mercantil_payment_traces" ("id" uuid NOT NULL, "shopcartId" character varying(100) NOT NULL, "clientId" character varying(100), "dniType" character varying(20), "dniNumber" character varying(50), "stage" character varying(50) NOT NULL, "status" character varying(20) NOT NULL, "message" character varying(500) NOT NULL, "errorCode" character varying(100), "errorStack" text, "payload" text, "response" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b65234b3ac74f4c4f152e2c384c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_77b0df4afd064c476ae7445421" ON "mercantil_payment_traces"  ("shopcartId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7263fb2765c1e7200e1f113392" ON "mercantil_payment_traces"  ("clientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1446084d4d547cb97b5dd1b84b" ON "mercantil_payment_traces"  ("dniType") `);
        await queryRunner.query(`CREATE INDEX "IDX_7b0d3ab4eefc3735c48f1b4fd1" ON "mercantil_payment_traces"  ("dniNumber") `);
        await queryRunner.query(`CREATE TABLE "mercantil_payments" ("id" uuid NOT NULL, "shopcartId" character varying(100) NOT NULL, "clientId" character varying(100), "paymentMethod" character varying(50) NOT NULL, "payerDocType" character varying(20), "payerDocNumber" character varying(50), "payerFirstName" character varying(255), "payerLastName" character varying(255), "debitBankCode" character varying(20), "debitValidationType" character varying(50), "debitPayerIdentifier" character varying(50), "debitToken" character varying(20), "cardNumber" character varying(50), "cardExpiryDate" character varying(10), "cardBankCode" character varying(20), "cardType" character varying(20), "accountPhone" character varying(20), "selectedBanks" text, "amount" numeric(15,2), "status" character varying(50) NOT NULL, "concept" character varying(255), "provider" character varying(100), "rawData" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_73670302cb4610d3a8aa37a9866" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a7b2898895a64837485b113ac4" ON "mercantil_payments"  ("shopcartId") `);
        await queryRunner.query(`CREATE TABLE "mercantil_policies" ("id" uuid NOT NULL, "shopcartId" character varying(100) NOT NULL, "clientId" character varying(100), "dniType" character varying(20), "dniNumber" character varying(50), "policyId" character varying(100) NOT NULL, "policyNumber" character varying(100), "number" character varying(100), "entity" character varying(20), "area" character varying(20), "certificateNumber" character varying(100), "title" character varying(255), "status" character varying(50), "paymentFrequency" character varying(50), "assuredSum" numeric(15,2), "quotedAmount" numeric(15,2), "annualPremium" numeric(15,2), "startDate" character varying(50), "endDate" character varying(50), "rawData" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6e1d75c763b3e562e843feb38d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0c30084363a470627d0f7cd8b4" ON "mercantil_policies"  ("shopcartId") `);
        await queryRunner.query(`CREATE INDEX "IDX_043d9bdc71a7ccaa53d1e980e0" ON "mercantil_policies"  ("clientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_53fc8c03027474416a401cdb4f" ON "mercantil_policies"  ("dniType") `);
        await queryRunner.query(`CREATE INDEX "IDX_77998377942a78d69c56084829" ON "mercantil_policies"  ("dniNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_e2babe0134800180ad87689acc" ON "mercantil_policies"  ("policyId") `);
        await queryRunner.query(`CREATE TABLE "mercantil_vehicles" ("id" uuid NOT NULL, "shopcartId" character varying(100) NOT NULL, "clientId" character varying(100), "policyId" character varying(100), "vehicleTypeId" character varying(100), "year" character varying(10) NOT NULL, "brandCode" character varying(100) NOT NULL, "brandName" character varying(255), "modelCode" character varying(100) NOT NULL, "modelName" character varying(255), "versionCode" character varying(100) NOT NULL, "versionName" character varying(255), "commonLocationId" character varying(100), "commonLocationName" character varying(255), "isArmored" boolean DEFAULT false, "plate" character varying(10), "colorId" character varying(100), "colorName" character varying(255), "chassisSerial" character varying(17), "engineSerial" character varying(18), "rawData" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fc06f95422204be3b880d32f91a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8c8a37b9c2953df633e63a0d78" ON "mercantil_vehicles"  ("shopcartId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f85e4faddaf52ee8f1f76fd1fc" ON "mercantil_vehicles"  ("clientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1c41625b9570a504636bda8bfa" ON "mercantil_vehicles"  ("plate") `);
        await queryRunner.query(`CREATE TABLE "payments"."exchange_rate" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "effective_date" date NOT NULL, "bolivares_per_usd" numeric(14,4) NOT NULL, "source" character varying(50), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "currency_id" uuid NOT NULL, CONSTRAINT "UQ_exchange_rate_currency_effective_date" UNIQUE ("currency_id", "effective_date"), CONSTRAINT "PK_5c5d27d2b900ef6cdeef0398472" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payments"."currency" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(50) NOT NULL, "code" character varying(3) NOT NULL, "symbol" character varying(5) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_723472e41cae44beb0763f4039c" UNIQUE ("code"), CONSTRAINT "PK_3cda65c731a6264f0e444cc9b91" PRIMARY KEY ("id")); COMMENT ON COLUMN "payments"."currency"."name" IS 'Nombre visible de la moneda (ej. Dólar, Bolívar)'; COMMENT ON COLUMN "payments"."currency"."code" IS 'Código ISO de la moneda (ej. USD, VES)'; COMMENT ON COLUMN "payments"."currency"."symbol" IS 'Símbolo de la moneda (ej. $, Bs.)'`);
        await queryRunner.query(`CREATE TABLE "payments"."payment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "amount_bs" numeric(15,2) NOT NULL, "amount_usd" numeric(10,2) NOT NULL DEFAULT '0', "reference" character varying(100), "billing_id" character varying(100) NOT NULL, "payment_date" TIMESTAMP WITH TIME ZONE NOT NULL, "external_source_bank_code" character varying(4), "external_source_account" character varying(20), "external_source_phone" character varying(20), "external_source_doc_type" character(1), "external_source_doc" character varying(20), "external_dest_bank_code" character varying(4), "external_dest_account" character varying(20), "external_dest_phone" character varying(20), "external_dest_doc_type" character(1), "external_dest_doc" character varying(20), "payer_user_id" character varying(100), "payer_name" character varying(150), "enterprise_id" character varying(100), "payment_status_id" integer NOT NULL, "payment_method_id" integer NOT NULL, "payment_type_id" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "internal_source_account_id" uuid, "internal_dest_account_id" uuid, "currency_id" uuid NOT NULL, CONSTRAINT "PK_fcaec7df5adf9cac408c686b2ab" PRIMARY KEY ("id")); COMMENT ON COLUMN "payments"."payment"."payer_user_id" IS 'Identificador de usuario en base de datos externa'`);
        await queryRunner.query(`CREATE TABLE "payments"."bank_account_type" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tipo_cuenta" character varying(50) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_45c7f031f07ed7551eb0a666b20" UNIQUE ("tipo_cuenta"), CONSTRAINT "PK_3bc977177ee05491337e4e67c0d" PRIMARY KEY ("id")); COMMENT ON COLUMN "payments"."bank_account_type"."tipo_cuenta" IS 'Tipo de cuenta bancaria (ej. Corriente, Ahorro)'`);
        await queryRunner.query(`CREATE TABLE "payments"."payment_method" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(40) NOT NULL, "name" character varying(120) NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_9277a41c2299387b03dfa049a58" UNIQUE ("code"), CONSTRAINT "PK_7744c2b2dd932c9cf42f2b9bc3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payments"."bank_payment_method" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "is_active" boolean NOT NULL DEFAULT true, "is_external" boolean NOT NULL DEFAULT false, "external_provider" character varying(120), "external_metadata" jsonb, "config" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "bank_id" uuid NOT NULL, "payment_method_id" uuid NOT NULL, CONSTRAINT "UQ_bank_payment_method_bank_method" UNIQUE ("bank_id", "payment_method_id"), CONSTRAINT "PK_98d58526664349aea367bb0eff2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payments"."bank" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bank_code" character varying(4) NOT NULL, "bank_name" character varying(120) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_257014cf4e9cc6aa52f12fb3105" UNIQUE ("bank_code"), CONSTRAINT "UQ_400774b79345dbdaf68740f9f17" UNIQUE ("bank_name"), CONSTRAINT "PK_7651eaf705126155142947926e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payments"."bank_account" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "numero_cuenta" character varying(20), "tipo_documento" character(1) NOT NULL, "documento" character varying(20) NOT NULL, "telefono_pago_movil" character varying(20), "telefono_validacion" character varying(20), "razon_social" character varying(255), "descripcion" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "bank_id" uuid NOT NULL, "account_type_id" uuid, "currency_id" uuid NOT NULL, CONSTRAINT "PK_f3246deb6b79123482c6adb9745" PRIMARY KEY ("id")); COMMENT ON COLUMN "payments"."bank_account"."telefono_pago_movil" IS 'Teléfono para pago móvil'; COMMENT ON COLUMN "payments"."bank_account"."telefono_validacion" IS 'Teléfono usado para validación adicional'; COMMENT ON COLUMN "payments"."bank_account"."razon_social" IS 'Razón social del titular (nombre o razón social)'`);
        await queryRunner.query(`CREATE TABLE "payments"."api_key" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "commerce_key" character varying(255) NOT NULL, "secret_key" character varying(255), "extra_key" character varying(255), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "bank_account_id" uuid NOT NULL, CONSTRAINT "PK_b1bd840641b8acbaad89c3d8d11" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "payments"."exchange_rate" ADD CONSTRAINT "FK_9cc0c5ab693ad206273ca2dadb8" FOREIGN KEY ("currency_id") REFERENCES "payments"."currency"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments"."payment" ADD CONSTRAINT "FK_dbfd535cca87acecf5adab80214" FOREIGN KEY ("internal_source_account_id") REFERENCES "payments"."bank_account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments"."payment" ADD CONSTRAINT "FK_07b8074031c9aecf2bb568e7ad7" FOREIGN KEY ("internal_dest_account_id") REFERENCES "payments"."bank_account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments"."payment" ADD CONSTRAINT "FK_0c2788c000c47176b48596cad1a" FOREIGN KEY ("currency_id") REFERENCES "payments"."currency"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments"."bank_payment_method" ADD CONSTRAINT "FK_52c31ec8cd564ab017902490293" FOREIGN KEY ("bank_id") REFERENCES "payments"."bank"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments"."bank_payment_method" ADD CONSTRAINT "FK_77a933c07494f020c902ea48b6a" FOREIGN KEY ("payment_method_id") REFERENCES "payments"."payment_method"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments"."bank_account" ADD CONSTRAINT "FK_24569b6843af6bcef189740e99e" FOREIGN KEY ("bank_id") REFERENCES "payments"."bank"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments"."bank_account" ADD CONSTRAINT "FK_bank_account_account_type_id" FOREIGN KEY ("account_type_id") REFERENCES "payments"."bank_account_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments"."bank_account" ADD CONSTRAINT "FK_4d57ed8a02fef8317e1a3da005c" FOREIGN KEY ("currency_id") REFERENCES "payments"."currency"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments"."api_key" ADD CONSTRAINT "FK_6994d05336196994fbffd5880c8" FOREIGN KEY ("bank_account_id") REFERENCES "payments"."bank_account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`INSERT INTO "payments"."payment_method" ("code", "name", "description", "is_active") VALUES ('p2p', 'Pago Móvil P2P', 'Pago móvil entre personas', true), ('c2p', 'Pago Móvil C2P', 'Pago móvil de cliente a comercio', true), ('transfer', 'Transferencia Bancaria', 'Transferencia entre cuentas bancarias', true) ON CONFLICT ("code") DO NOTHING`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "payments"."api_key" DROP CONSTRAINT "FK_6994d05336196994fbffd5880c8"`);
        await queryRunner.query(`ALTER TABLE "payments"."bank_account" DROP CONSTRAINT "FK_4d57ed8a02fef8317e1a3da005c"`);
        await queryRunner.query(`ALTER TABLE "payments"."bank_account" DROP CONSTRAINT "FK_bank_account_account_type_id"`);
        await queryRunner.query(`ALTER TABLE "payments"."bank_account" DROP CONSTRAINT "FK_24569b6843af6bcef189740e99e"`);
        await queryRunner.query(`ALTER TABLE "payments"."bank_payment_method" DROP CONSTRAINT "FK_77a933c07494f020c902ea48b6a"`);
        await queryRunner.query(`ALTER TABLE "payments"."bank_payment_method" DROP CONSTRAINT "FK_52c31ec8cd564ab017902490293"`);
        await queryRunner.query(`ALTER TABLE "payments"."payment" DROP CONSTRAINT "FK_0c2788c000c47176b48596cad1a"`);
        await queryRunner.query(`ALTER TABLE "payments"."payment" DROP CONSTRAINT "FK_07b8074031c9aecf2bb568e7ad7"`);
        await queryRunner.query(`ALTER TABLE "payments"."payment" DROP CONSTRAINT "FK_dbfd535cca87acecf5adab80214"`);
        await queryRunner.query(`ALTER TABLE "payments"."exchange_rate" DROP CONSTRAINT "FK_9cc0c5ab693ad206273ca2dadb8"`);
        await queryRunner.query(`DROP TABLE "payments"."api_key"`);
        await queryRunner.query(`DROP TABLE "payments"."bank_account"`);
        await queryRunner.query(`DROP TABLE "payments"."bank"`);
        await queryRunner.query(`DROP TABLE "payments"."bank_payment_method"`);
        await queryRunner.query(`DROP TABLE "payments"."payment_method"`);
        await queryRunner.query(`DROP TABLE "payments"."bank_account_type"`);
        await queryRunner.query(`DROP TABLE "payments"."payment"`);
        await queryRunner.query(`DROP TABLE "payments"."currency"`);
        await queryRunner.query(`DROP TABLE "payments"."exchange_rate"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1c41625b9570a504636bda8bfa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f85e4faddaf52ee8f1f76fd1fc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c8a37b9c2953df633e63a0d78"`);
        await queryRunner.query(`DROP TABLE "mercantil_vehicles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e2babe0134800180ad87689acc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77998377942a78d69c56084829"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_53fc8c03027474416a401cdb4f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_043d9bdc71a7ccaa53d1e980e0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0c30084363a470627d0f7cd8b4"`);
        await queryRunner.query(`DROP TABLE "mercantil_policies"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7b2898895a64837485b113ac4"`);
        await queryRunner.query(`DROP TABLE "mercantil_payments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b0d3ab4eefc3735c48f1b4fd1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1446084d4d547cb97b5dd1b84b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7263fb2765c1e7200e1f113392"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77b0df4afd064c476ae7445421"`);
        await queryRunner.query(`DROP TABLE "mercantil_payment_traces"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a07a882a57a7a3dd9572689580"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_15fab6ed169599f440d983adca"`);
        await queryRunner.query(`DROP TABLE "mercantil_payment_quotes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85ec7fc5de58d0cf8043e5adfd"`);
        await queryRunner.query(`DROP TABLE "mercantil_clients"`);
    }

}
